security:
    enable_authenticator_manager: true
    providers:
        users:
            entity:
                class: 'App\Entity\Mailbox'

    password_hashers:
        App\Entity\Mailbox:
            id: App\Security\DovecotPasswordEncoder

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
#        main:
#            anonymous: true
#            lazy: true
#            provider: users
#            form_login:
#                login_path: login
#                check_path: login
#            guard:
#                authenticators:
#                    - App\Security\LoginFormAuthenticator
#            logout:
#                path: app_logout

    access_control:
#        - { path: ^/login }
#        - { path: ^/, roles: ROLE_ADMIN }
